### ISSUE TITLE
pre-allocation issue in PosteriorDraw.nonconjugate

### ISSUE THREAD

**Issue by FinYang** [dm13450/dirichletprocess#11]
Hi there, 

Spotted this when going through the code. 
In `PosteriorDraw.nonconjugate` there is a line as a pre-allocation of `theta` before the loop.
https://github.com/dm13450/dirichletprocess/blob/eccaaec0d3dba2b5b1637d5fe23ec49244ed52ce/R/mixing_distribution_posterior_draw.R#L25

Then later the length of the loop is essentially the length of `mh_result$parameter_samples` instead of `mh_result`.
https://github.com/dm13450/dirichletprocess/blob/eccaaec0d3dba2b5b1637d5fe23ec49244ed52ce/R/mixing_distribution_posterior_draw.R#L27

It doesn't break anything since it's a list but I figured I should let you know.

**Comment by dm13450** [comment]
Another good spot, I've also fixed this.
