### ISSUE TITLE
Limit on  the post_draws in Initialise

### ISSUE THREAD

**Issue by FinYang** [dm13450/dirichletprocess#12]
Hi there, 

A question when I trying to do my own mixture model. 

https://github.com/dm13450/dirichletprocess/blob/9dc58085df5cd24d8959fac3f82733b9f62e224f/R/initialise.R#L45-L53

I am doing a non-conjugate mixture so that means `Initialise` will try to do `MetropolisHastings`. On line 52 and 53, `dpObj$clusterParameters` takes the first two parameters drawn from `post_draws`. If I understand the function correctly, isn't it restricting the model to have only two parameters? I have quite a bit parameters so I kept hitting the wall until I pinned it down to these two lines. 

Thanks.

**Comment by dm13450** [comment]
Good spot. I've pushed a fix, so install the dev version and hopefully it should now work.
