### ISSUE TITLE
dirichletprocess.rdb is corrupt

### ISSUE THREAD

**Issue by SwaggerNiels** [dm13450/dirichletprocess#13]
```
Error: package or namespace load failed for ‘dirichletprocess’ in get(method, envir = home):
lazy-load database '/home/nburghoorn/R/x86_64-pc-linux-gnu-library/3.6/dirichletprocess/R/dirichletprocess.rdb' is corrupt
```

is what I get when I:

`library(dirichletprocess)`

for both the stable and dev installations.
Restarting/refreshing my Rstudio session doesn't work.
What could be happening?

**Comment by dm13450** [comment]
Restart your R session and try again please

**Comment by SwaggerNiels** [comment]
Restarting/refreshing my Rstudio session doesn't work.^^

**Comment by dm13450** [comment]
Remove, reinstall and try again. I don't think this is an issue specific to this package but something related to your R installation. Try loading it outside of RStudio too

**Comment by SwaggerNiels** [comment]
Mb -->
for others using Rstudio online:

`.rs.restartR()`

It worked thanks!
