### ISSUE TITLE
Only symmetric kernels supported for proposals in Metropolis-Hastings algorithm

### ISSUE THREAD

**Issue by lbelzile** [dm13450/dirichletprocess#15]
Thank you for this very nice package. I was looking into the accompanying vignette to implement a new Dirichlet process mixture with a non-conjugate prior and I stumbled upon the `MhParameterProposal.` function (the example uses a random walk with a folded normal distribution). 

It seems that only symmetric kernels are supported since the code in `metropolis_hastings.R` does not include a Hastings ratio. While this may be intentional, I could not see it mentioned in the vignette, the documentation or the examples. Perhaps worth adding a note to this effect?

**Comment by dm13450** [comment]
Yeah thanks for picking this up, I'll make the correction. 
Pull requests welcome though if you manage to implement your new mixture!
