### ISSUE TITLE
Error in y[which(clusterLabels == i), , drop = FALSE] :    subscript out of bounds

### ISSUE THREAD

**Issue by nick-torenvliet** [dm13450/dirichletprocess#16]
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
require(dirichletprocess)
require(ggplot2)
require(dplyr)
require(tidyr)
numIts <- 1000
faithfulTrans <- scale(faithful)
dp <- DirichletProcessMvnormal(faithfulTrans)
dp <- Fit(dp, numIts)
plot(dp)
dp2 <- DirichletProcessMvnormal(faithfulTrans, numInitialClusters = nrow(faithfulTrans))
dp2 <- Fit(dp2, numIts)
plot(dp2)

From the tutorial, bails with, Error in y[which(clusterLabels == i), , drop = FALSE] : 
  subscript out of bounds.  It doesn't matter what value I set numInitialClusters to.

**Comment by dm13450** [comment]
This is fixed in the dev version. This will be released to CRAN asap
