### ISSUE TITLE
Problem with convergence of the likelihoodChain

### ISSUE THREAD

**Issue by filippofiocchi** [dm13450/dirichletprocess#20]
Hello,
thank for the great package, it has been very usefull, easy to use and great to learn about DPMM.

I'm using your packages, but when I run more chains to cheack for convergence, even with relative simple data-set as Iris, the Gelman plot says : 'Cannot compute Gelman & Rubin's diagnostic for any chain segments for variables Likelihood. This indicates convergence failure'.

I think it'is due to the fact that some times the likelihoodChain estimate is -Inf. I try to run longer chain but it didn't solve the problem.

There is a way to solve this? For example, can I take out all the values in the chain with -Inf (I don't know if this is correct from a theory point of view) ?

Thank again for the great packages!!

**Comment by dm13450** [comment]
I'd start with looking at what parameters are causing the likelihood to give a -Inf value and think about whether you should change your prior distribution to make sure those values of the parameters can't occur. 

It could be that the Inf's are early on in the chain, so you discard an early part of the chain and only look at the values once its established itself. 

But if all else fails, you can replaces the -Infs with a large value, say -1e12. Something that is essentially infinite compared to your other values. 

Hope this helps!

**Comment by filippofiocchi** [comment]
Thank you 👍

**Comment by filippofiocchi** [comment]
Hello,
I tried your idea of changing the prior and it kinds of improve things, but it didn't eliminate the problem.
Below I will try to be more precise of what is the problem, and I may have found a solution. But I am not sure of it, and that's not my intention to diminish your package, that I still think is great.

```
library(mvtnorm)
library(dirichletprocess)


n1 <- 100
R1 <- matrix(c(1,0,0,1), nrow=2,ncol=2)
mu1 <- c(0,0)
data1 <- rmvnorm(n1,mu1,R1)

n2 <- 200
R2 <- matrix(c(1,0,0,1), nrow=2,ncol=2)
mu2 <- c(5,5)
data2 <- rmvnorm(n2,mu2,R2)
data <- rbind(data1,data2)
plot(data)

dpCluster <-  DirichletProcessMvnormal(data)
dpCluster <- Fit(dpCluster, 1000,progressBar = TRUE)
which(dpCluster$likelihoodChain==-Inf)
```

The algorithm work fine, it finds the right number of clusters, but some value in the likelihoodChain are -Inf. So I read the code of the functions Fit, likelikood, mvnormal_normal_wishart. And I may have found the problem in the function likelihood and Fit, or it may be that I did't understand the code. In the function LikelihoodDP, before the calculation of the density, instead of extracting the parameter of the different clusters , it extracts the parameters of the cluster to which each point was assign: 
`
```
allParameters <- lapply(seq_along(dpobj$clusterParameters),
                          function(i) dpobj$clusterParameters[[i]][,,dpobj$clusterLabels, drop=FALSE])

```
This result in a matrix n x n, with a lot of repetitions because more points belong to the same cluster, instead of a matrix n x k (k are the different clusters) that is used correctly in the ClusterComponentUpdate function when you calculate the new probabilities of assigment.
The second problem is in the Fit function where the likelihood is simplly calculated by sum of the log of the matrix n x n, because the likelihood of a Gaussian mixture should be calculated as : 
![image](https://user-images.githubusercontent.com/52209617/117614971-617a0080-b169-11eb-9d87-cc4a4123ec64.png)
and if we want to take the log : 
![image](https://user-images.githubusercontent.com/52209617/117615067-82425600-b169-11eb-9b1c-704581bd1c92.png)
So for each iteration of the chain, assuming to have the matrix n x k (for each data point a vector with the k densities, one for each cluster), we should multiply for each data points the weights of the clusters with the densities, then sum the element vector 1x k (now I am using one point at the time), and this correspont to the sum in K of the images above. After that it should take the product of all points, or the sum of the log.
I try to code: 

```
My_likelihood <- function(dp,weightsChain){
  likelihood_value <- c()
  data <- dp$data
  theta <- dp$clusterParameters
  y <- vapply(seq_len(dim(theta[[1]])[3]),
              function(i) mvtnorm::dmvnorm(data,
                                           theta[[1]][,, i],
                                           theta[[2]][, , i]),
              numeric(nrow(data)))
  for(i in seq(nrow(data))){
    likelihood_value[i] <- sum(weightsChain*y[i,])
  }
  return(sum(log(likelihood_value)))
}
```


Then I add this function at the Fit function on my global environment, and run again the chain, now there aren't -Inf values, and running multiple chains the gelman plot work.
Apart from the n x n matrix of densities, and the multiplication with the weights, I think that the real problem for the -Inf, was that  the Fit function take the log of all the element of the matrix and then sum them. By doing that , if a single point has a very low density with respect to some distant cluster, the log of that density became -Inf and the sum of all the element of the matrix became -Inf.
While before it should sum the columns together, then it should take the log and sum all the rows.

I am sorry for the long issue, and I may be wrong about everything, but I want to understand why even for easy simulation the likelihood continued to diverge.

Thank again for the previous feedbacks and the pacakge.

**Comment by dm13450** [comment]
Thanks for this and I appreciate the time and effort you've put in trying to correct the issue. 

I think you are correct. My current implementation is only looking at the likelihood of each point with its own cluster parameter rather than all the cluster parameters. It's a bit a bug/undefined behaviour to do with it not vectorising over x. 

Thankfully this doesn't affect the underlying algorithm, just the likelihood calculation in the Fit function. 

Can you raise a pull request of the changes you think should go in? 
It'll need to be generic for all the mixture models, so will use the `Likelihood(mdobj, x, theta)` function. 

Let me know if you need help, I'm happy to work with you to get this fixed!
