### ISSUE TITLE
HDP Fit function returns an empty object with an error when accessed

### ISSUE THREAD

**Issue by majaidi** [dm13450/dirichletprocess#24]
Hi 

I have tried to run the following code from the package

>N <- 300
#Sample N random uniform U
U <- runif(N)
group1 <- matrix(nrow=N, ncol=2)
group2 <- matrix(nrow=N, ncol=2)
#Sampling from the mixture

>m1 <- c(-2,-2)
>m2 <- c(2,2)

>for(i in 1:N){
  if(U[i]<.3){
    group1[i,] <- mvtnorm::rmvnorm(1,m1)
    group2[i,] <- mvtnorm::rmvnorm(1,m1)
  }else if(U[i]<0.7){
    group1[i,] <- mvtnorm::rmvnorm(1,m2)
    group2[i,] <- mvtnorm::rmvnorm(1,m1)
  }else {
    group1[i,] <- mvtnorm::rmvnorm(1,m2)
    group2[i,] <- mvtnorm::rmvnorm(1,m2)
  }
}

> data_hdp <- list(group1, group2)

> hdp_mvnorm <- DirichletProcessHierarchicalMvnormal2(dataList =  data_hdp)

> system.time(
  hdp_mvnorm <- Fit(hdp_mvnorm, 500)
)
`

The algorithm takes some time to run with the following error from the returned object

> hdp_mvnorm
Dirichlet process object run for 0 iterations.
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

Please let me know if this is something you can help with 

Regards
Amine

**Comment by dm13450** [comment]
Good news, this is just a bug with the printing method, so everything is working correctly, you can interact with the DP object as needed, you just can't write `hdp_mvnorm` in the REPL. 

I'm pushing a fix shortly, but overall, you can carry on with your analysis.

**Comment by majaidi** [comment]
Awesome! Thanks for checking it out much appreciated.
