### ISSUE TITLE
wrong number of dimensions from LikelihoodDP()

### ISSUE THREAD

**Issue by sergioventurini** [dm13450/dirichletprocess#26]
Hi everybody,

first let me thank you for the very nice package!

In the `LikelihoodDP()` function code it is stated that the `likelihoodValues` object should be an "n x k matrix". However, while using the package, I noticed that this does not seem to be true. I used it with the following simple example, which I debugged line by line:

`library(dirichletprocess)`

`set.seed(1406)`
`n <- 10`
`y <- rt(n, 3) + 2`

`g0Priors <- c(0, 1, 1, 1)`
`alphaPriors <- c(2, 4)`

`mdobj <- GaussianMixtureCreate(g0Priors)`
`dpobj <- DirichletProcessCreate(y, mdobj, alphaPriors)`
`dpobj <- Initialise(dpobj)`

`debugonce(Fit)`
`dp <- Fit(dpobj, 10)`

My guess is that the `Likelihood.normal()` function uses a definition of the parameters that is not appropriate (their values are replicated according to some rules that do not appear to be the right ones).

Is there any chance that you check it and get back with a response? I would like to use the package for my research, but I need to be sure that it provides the right numbers.

Thanks in advance for your answer.

Sergio

**Comment by dm13450** [comment]
Hey thanks for raising this, I can replicate the issue and will get it fixed.

**Comment by dm13450** [comment]
Fixed in the latest release

**Comment by sergioventurini** [comment]
I noticed that in the latest release the LikelihoodDP() function resizes the `likelihoodValues` object using the code

`dim(likelihoodValues) <- c(nrow(dpobj$data), dpobj$numberClusters)`

but this shuffles the values in a strange way. I think it should be replaced by something like

`likelihoodValues <- matrix(likelihoodValues, nrow = dpobj$n, ncol = dpobj$numberClusters, byrow = TRUE)`

Looking forward to know what do you think about it. Thanks!
